#!/bin/bash

# Base URL for local development
BASE_URL="http://localhost:7071/api"

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${GREEN}Feedback Loops Java - API Test Commands${NC}"
echo "=================================================="

echo -e "\n${YELLOW}1. Add a new podcast${NC}"
echo "curl -X POST $BASE_URL/add-podcast \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"title\": \"The Future of AI in Healthcare\","
echo "    \"transcript\": \"This episode explores how artificial intelligence is revolutionizing healthcare. We discuss machine learning applications in diagnostics, personalized medicine, and patient care. The conversation covers current challenges and future opportunities in AI-driven healthcare solutions.\""
echo "  }'"

echo -e "\n${YELLOW}2. Update user listening history${NC}"
echo "curl -X POST $BASE_URL/update-user-history \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"userId\": \"1\","
echo "    \"listeningHistory\": \"Interested in AI, machine learning, healthcare technology, and medical innovations.\""
echo "  }'"

echo -e "\n${YELLOW}3. Get podcast recommendations for user${NC}"
echo "curl -X GET \"$BASE_URL/recommend-podcasts?userId=1\""

echo -e "\n${YELLOW}4. Get suggested podcasts for user${NC}"
echo "curl -X GET \"$BASE_URL/get-suggested-podcasts?userId=1\""

echo -e "\n${GREEN}Example: Add multiple podcasts${NC}"
echo "----------------------------------------"

echo -e "\n${YELLOW}Add Robotics Podcast:${NC}"
echo "curl -X POST $BASE_URL/add-podcast \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"title\": \"Robotics Revolution\","
echo "    \"transcript\": \"Join us as we dive deep into the world of robotics and automation. This episode covers the latest advances in robotic technology, from industrial automation to personal assistants. We explore how robots are changing manufacturing, healthcare, and daily life.\""
echo "  }'"

echo -e "\n${YELLOW}Add Space Exploration Podcast:${NC}"
echo "curl -X POST $BASE_URL/add-podcast \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"title\": \"Journey to Mars\","
echo "    \"transcript\": \"This fascinating episode takes listeners on a journey through space exploration and Mars colonization efforts. We discuss SpaceX missions, NASA projects, and the challenges of interplanetary travel. The conversation includes insights from aerospace engineers and space scientists.\""
echo "  }'"

echo -e "\n${YELLOW}Add Climate Change Podcast:${NC}"
echo "curl -X POST $BASE_URL/add-podcast \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"title\": \"Climate Solutions Today\","
echo "    \"transcript\": \"An in-depth discussion about renewable energy technologies, carbon capture innovations, and sustainable practices. We explore how governments and corporations are tackling climate change through policy and technology. Featured guests include environmental scientists and clean energy entrepreneurs.\""
echo "  }'"

echo -e "\n${YELLOW}Add Quantum Computing Podcast:${NC}"
echo "curl -X POST $BASE_URL/add-podcast \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"title\": \"Quantum Leap\","
echo "    \"transcript\": \"Dive into the world of quantum computing and quantum physics. This episode explains quantum supremacy, quantum algorithms, and their potential impact on cryptography, drug discovery, and optimization problems. We interview leading quantum researchers and industry experts.\""
echo "  }'"

echo -e "\n${YELLOW}Add Cryptocurrency Podcast:${NC}"
echo "curl -X POST $BASE_URL/add-podcast \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"title\": \"Blockchain Futures\","
echo "    \"transcript\": \"Exploring the evolution of cryptocurrency, blockchain technology, and decentralized finance. We discuss Bitcoin, Ethereum, smart contracts, and the future of digital currencies. Guests include crypto traders, blockchain developers, and financial technology experts.\""
echo "  }'"

echo -e "\n${YELLOW}Add Mental Health Podcast:${NC}"
echo "curl -X POST $BASE_URL/add-podcast \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"title\": \"Mind Matters\","
echo "    \"transcript\": \"A comprehensive look at mental health awareness, therapy techniques, and wellness strategies. We cover topics like anxiety management, depression treatment, mindfulness practices, and the importance of mental health in the workplace. Professional therapists and psychologists share their insights.\""
echo "  }'"

echo -e "\n${YELLOW}Add Cybersecurity Podcast:${NC}"
echo "curl -X POST $BASE_URL/add-podcast \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"title\": \"Digital Defense\","
echo "    \"transcript\": \"Understanding cybersecurity threats, data protection, and privacy in the digital age. We discuss hacking prevention, secure coding practices, and corporate security strategies. Cybersecurity experts share real-world case studies and best practices for staying safe online.\""
echo "  }'"

echo -e "\n${YELLOW}Add Entrepreneurship Podcast:${NC}"
echo "curl -X POST $BASE_URL/add-podcast \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"title\": \"Startup Stories\","
echo "    \"transcript\": \"Inspiring stories from successful entrepreneurs and startup founders. We explore the challenges of building a business, securing funding, scaling operations, and navigating market competition. Featured guests share their journey from idea to IPO.\""
echo "  }'"

echo -e "\n${YELLOW}Add Food Science Podcast:${NC}"
echo "curl -X POST $BASE_URL/add-podcast \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"title\": \"Future of Food\","
echo "    \"transcript\": \"Exploring innovations in food technology, sustainable agriculture, and nutrition science. We discuss lab-grown meat, vertical farming, food security, and the role of technology in feeding the growing global population. Food scientists and agricultural experts share their research.\""
echo "  }'"

echo -e "\n${YELLOW}Add Education Technology Podcast:${NC}"
echo "curl -X POST $BASE_URL/add-podcast \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"title\": \"Learning Revolution\","
echo "    \"transcript\": \"How technology is transforming education through online learning, virtual reality, and personalized learning platforms. We explore the impact of AI tutors, digital classrooms, and remote education on students and teachers worldwide. Educational technologists and teachers share their experiences.\""
echo "  }'"

echo -e "\n${GREEN}Example: Update different users${NC}"
echo "----------------------------------------"

echo -e "\n${YELLOW}Update User 2 (Space enthusiast):${NC}"
echo "curl -X POST $BASE_URL/update-user-history \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"userId\": \"2\","
echo "    \"listeningHistory\": \"Fascinated by space exploration, astronomy, astrophysics, and Mars colonization projects.\""
echo "  }'"

echo -e "\n${YELLOW}Update User 3 (Health focused):${NC}"
echo "curl -X POST $BASE_URL/update-user-history \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"userId\": \"3\","
echo "    \"listeningHistory\": \"Interested in fitness, nutrition, mental health, and wellness technologies.\""
echo "  }'"

echo -e "\n${YELLOW}Update User 4 (Tech entrepreneur):${NC}"
echo "curl -X POST $BASE_URL/update-user-history \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"userId\": \"4\","
echo "    \"listeningHistory\": \"Passionate about startups, entrepreneurship, business strategy, and venture capital.\""
echo "  }'"

echo -e "\n${YELLOW}Update User 5 (Climate researcher):${NC}"
echo "curl -X POST $BASE_URL/update-user-history \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"userId\": \"5\","
echo "    \"listeningHistory\": \"Focused on environmental science, renewable energy, climate change solutions, and sustainability.\""
echo "  }'"

echo -e "\n${YELLOW}Update User 6 (Crypto trader):${NC}"
echo "curl -X POST $BASE_URL/update-user-history \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"userId\": \"6\","
echo "    \"listeningHistory\": \"Active in cryptocurrency trading, blockchain technology, DeFi protocols, and digital assets.\""
echo "  }'"

echo -e "\n${YELLOW}Update User 7 (Cybersecurity expert):${NC}"
echo "curl -X POST $BASE_URL/update-user-history \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"userId\": \"7\","
echo "    \"listeningHistory\": \"Specializes in cybersecurity, ethical hacking, data privacy, and information security.\""
echo "  }'"

echo -e "\n${YELLOW}Update User 8 (Quantum physicist):${NC}"
echo "curl -X POST $BASE_URL/update-user-history \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"userId\": \"8\","
echo "    \"listeningHistory\": \"Deep interest in quantum computing, quantum physics, advanced mathematics, and theoretical computer science.\""
echo "  }'"

echo -e "\n${GREEN}Testing Workflow${NC}"
echo "----------------------------------------"
echo "1. First, make sure your Azure Functions are running locally:"
echo "   mvn azure-functions:run"
echo ""
echo "2. Update your local.settings.json with valid Azure OpenAI credentials"
echo ""
echo "3. Run the add-podcast commands to populate some data"
echo ""
echo "4. Update user histories with different interests"
echo ""
echo "5. Call the recommend-podcasts endpoint to see personalized results"
echo ""
echo "6. Check get-suggested-podcasts to see the stored recommendations"

echo -e "\n${RED}Note: Make sure you have:${NC}"
echo "- Java 17+ installed"
echo "- Maven configured"
echo "- Azure Functions Core Tools installed"
echo "- Valid Azure OpenAI credentials in local.settings.json"
echo "- Neon database with proper schema and sample users"
